### ISSUE TITLE
Feedback Exposé 

### ISSUE THREAD

**Issue by angi-mrer** [sebfuh/EPWS2324Fuhrmann_Maurer#1]
Hallo Volker, hallo Mario,

Wir haben jetzt unser Exposé weiter/fertig überarbeitet und hätten dazu gerne ein kurzes Feedback bzgl. Inhalt und Aufbau. 
Inhaltlich haben wir uns eher kurz gehalten, ist das so in Ordnung? 
Bzgl. dem Aufbau habt ihr heute im Feedback gemeint, dass wir auf Stichpunkte verzichten sollen. Das haben wir soweit auch geändert, haben aber trotzdem eine Listenaufzählung für beispielsweise die Ziele gelassen, da das insgesamt übersichtlicher ist und schneller erkennbar ist was wir im Projekt erreichen wollen. Ist das so in Ordnung, oder sollen wir das komplette Exposé als Fließtext ausarbeiten? 

Das Exposé haben wir in unsere README eingefügt. 

@vschaefer @mariofaske 

Vielen Dank :)

Sebastian & Angelina

**Comment by mariofaske** [comment]
Hallo,

euer Exposé enthält ja schon zum Teil Lösungen. Woher wisst ihr, dass ihr auf jeden Fall einen Barcode-Scanner nutzen werdet oder überhaupt mit Barcodes arbeitet?

Ein Ziel eures Projektes sollte es sein, Möglichkeiten der Erfassung von Zutaten zu prüfen. Das Projekt bietet auch durchaus interessante Ansätze zum Thema IoT und Web. Euer Exposé liest sich so, als ob ihr schon genau wisst, wie euer System am Ende aussieht, und das ist nicht Ziel des Entwicklungsprojekts. Wo und wie kann man den noch Zutaten erfassen? 

Versucht erstmal allgemein das Problem zu beschreiben und dann eine Projektidee, ohne irgendwelche Lösungsansätze.

**Comment by angi-mrer** [comment]
Closed
