### ISSUE TITLE
Domänenmodelle Überarbeitung 

### ISSUE THREAD

**Issue by angi-mrer** [sebfuh/EPWS2324Fuhrmann_Maurer#3]
Hallo Mario, hallo Volker,

wir haben die Domänenmodelle nochmal überarbeitet und hätten dazu gerne nochmal ein Feedback :)

![epws2324-domaenenmodelle-fuhrmann-maurer](https://github.com/sebfuh/EPWS2324Fuhrmann_Maurer/assets/116002806/bb926642-bbc8-4953-9317-1968ab8ffdd5)

Vielen Dank!

Grüße
Angelina 

 @mariofaske @vschaefer

**Comment by vschaefer** [comment]
Hello,
das sieht aus meiner Sicht schon ganz gut aus.
Ich frage mich jedoch warum in beiden Modellen „Einkaufsbeleg” und „Produkte” gruppiert sind, aber keine Beziehung zueinander haben.
Die Entität „Lebensmitteleingabe” ist gerade noch eine Blackbox. Ihr könnt einmal prüfen ob es Sinn diese in mehrere Entitäten aufzusplitten.

**Comment by angi-mrer** [comment]
Hallo,

danke für die Antwort :)
Die Darstellung ist eher schlecht gewählt, ich habe es nun getrennt, da mir für die Gruppierung auch kein passender Name einfallen möchte. 
![deskriptiv-domaenenmodell-essen](https://github.com/sebfuh/EPWS2324Fuhrmann_Maurer/assets/116002806/120dc188-6e36-44e7-882c-7a1c920f6acf)
Ist das so besser?


Danke!

Grüße
Angelina
