### ISSUE TITLE
NodeJs - Express -CSS

### ISSUE THREAD

**Issue by angi-mrer** [sebfuh/EPWS2324Fuhrmann_Maurer#6]
Hallo Volker und Mario, @vschaefer @mariofaske 

bei der Erstellung der Anwendung haben wir das Problem, dass die CSS Dateien nicht integriert werden (Code: code/scripts/getFirebase.js & code/index.html & code/styles).
Wir haben schon mehrere Versuche gestartet, u.a. mit express.static, was leider auch nicht funktioniert hat. 

`app.use(express.static(path.join(__dirname, '../styles')));`

Könnt ihr uns dazu weiter helfen? Wäre schade wenn es final so aussehen würde...

Vielen Dank!

Grüße
Angelina

**Comment by vschaefer** [comment]
Hallo, wie kann ich eure Anwendung installieren und starten?

**Comment by angi-mrer** [comment]
Hallo Volker,
Das ganze wird mit node gestartet und auf der Seite localhost:3000/barcodes angezeigt.
Dazu installiert haben wir node, express und axios.

**Comment by vschaefer** [comment]
Hallo,

in den HTML Dateien stimmen die Pfade zu den CSS Dateien nicht.
Wenn ihr das `styles` Verzeichnis über `express.static` lädt, wird nicht das Verzeichnis selber bereitgestellt, sondern die darin enthaltenen Dateien.

An der Stelle empfehle ich euch einen weiteren Ordner `public` im Projektordner anzulegen, den `styles` Ordner dort hinein zu schieben und dann den `public` Ordner über `express.static` zu laden.

Zudem solltet ihr eine `package.json` erstellen, über die für das Projekt notwendigen Module schnell installiert werden können und auch die Anwendung über ein npm Befehl gestartet werden kann.

**Comment by angi-mrer** [comment]
Vielen Dank!
